/**
 * Nova's icon compatibility layer.
 *
 * Keeping icon aliases here lets the views stay focused on their domain while
 * the visual system uses one consistent Phosphor icon family.
 */
export {
  Heartbeat as Activity,
  Warning as AlertTriangle,
  Archive as ArchiveRestore,
  ArrowLeft,
  ArrowRight,
  ArrowUpLeft,
  Bell,
  BellRinging as BellRing,
  Robot as Bot,
  Stack as Boxes,
  CaretLeft as ChevronLeft,
  Check,
  CheckCircle as CheckCircle2,
  Gauge as CircleGauge,
  StopCircle as CircleStop,
  Clock as Clock3,
  Code as Code2,
  Command,
  Copy,
  Cpu,
  Database,
  Database as DatabaseBackup,
  DownloadSimple as Download,
  ArrowSquareOut as ExternalLink,
  File,
  FileArchive,
  FileCode as FileCode2,
  Funnel as Filter,
  FloppyDisk as Save,
  Folder,
  GearSix as Settings,
  GlobeHemisphereWest as Globe2,
  HardDrive,
  HardDrives as Server,
  ClockCounterClockwise as History,
  Key as KeyRound,
  Stack as Layers3,
  Lightning as Zap,
  SquaresFour as LayoutDashboard,
  CircleNotch as LoaderCircle,
  LockKey as LockKeyhole,
  SignOut as LogOut,
  List as Menu,
  Memory as MemoryStick,
  DotsThree as MoreHorizontal,
  SealCheck as PackageCheck,
  Package as PackageOpen,
  Play,
  Plus,
  Power,
  ArrowsClockwise as RefreshCcw,
  RocketLaunch as Rocket,
  ArrowClockwise as RotateCw,
  MagnifyingGlass as Search,
  SlidersHorizontal as Settings2,
  ShieldCheck,
  TerminalWindow as SquareTerminal,
  Trash as Trash2,
  CloudArrowUp as UploadCloud,
  UserCircle as UserRound,
  X,
} from "@phosphor-icons/react";

export { IconContext } from "@phosphor-icons/react";
